# multiple tests suites
# working example can be found at https://github.com/scottohara/loot

language: ruby

# Cache gems
cache:
  bundler: true

env:
  global:
    CC_TEST_REPORTER_ID=b2c51ead32a5ba146275df79c6929633c193991d3e902ef1ecde39c80e3fd5a6
  secure: "P4hrjc/4ieNkFk7kMztClFN37uCtF0Ywyk4iHvh3alXlQunDcMSLi/ZhfwiWKOyWPSYp3oG2yi9vltkLaFKTizJM6j2eIe4GLEt03H5zXKqeXmd/Rype1VPExTTA6waBRB+ccmqgUkOM6Y6sD1yTr4wQFs+hPOTZRzoZGUHyGGS4jnaAdixs9GWuQ4wNT9PPDucGWeOL5fN95z5uu3I0kgexFm73lM6R+R1JnGPuUXXy3XhxeuViiz89Wpgr9PSJM3EDPC/pbQe4Wg3v9b2A+cmKjl5P49Y65loTeGCIJC8xw9eo2mfbJirZO9Wf4c64Io4w3OvNirMdn2io8MT5wXxa8+Lwt0GdzToVWpWUbjMGbhXz/od4yW4saDdcR9QBp2sRrNXGXQsc461+oGhyFs4aS5ulUfTNIE8sy43tUkakGJcSc+xNecgaMImXBWShhIG54OZORYff01SP1JNVWEGADLJqF2mvdStOwycxjrHKu0Ra3oVFsR1h9fZt/kzD5RZyfVbUx9pS8sdpl/B6cXxqeG+GuUebvYUt/8r8pNukI8HEmEbtXP8qWQ2UZOyE9SdwUBPfOXWP6h3jrvtTmZgtUSocp8BlyolfgbNwPSdA/DPRQKDBzOF4hUJfBnEJE8Vx1I/noQ8IyVzYfiFMvPKH/T1aOrXmlP4ELFykNq8="

    
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}  # Install ruby gems, excluding production only gems such as unicorn (already present by default in Travis)

# Setup the database
before_script: bundle exec rake db:create db:migrate

# Run the test suites
script:
  - bundle exec cucumber
  - bundle exec rspec
  
# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
