language: ruby
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
    CC_TEST_REPORTER_ID=b2c51ead32a5ba146275df79c6929633c193991d3e902ef1ecde39c80e3fd5a6
    
before_install:
- nvm install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter

install:
- bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
- npm install                         # Install npm dependencies
#- npm install karma-firefox-launcher codeclimate-test-reporter
- gem install cucumber
- gem install rspec

script:
- bundle exec rake db:drop --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- npm test
- bundle exec rspec
- bundle exec cucumber

# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
