name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CCTR: ./cc-test-reporter
      CCTR_ID: "b27ddaa3e2284dc734d6b075bbf977e87c08861108dc5434a64c992c514bd43b"
      BUNDLE_WITHOUT: production
      #KEY: "c056e90b8efa7536c11ed963bfcfec12"

    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Set up Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    
    - name: Install bundler
      run: |
        gem install bundler
    - name: Install Dependencies
      run: bundle install
    - name: Set up test database
      run: bundle exec rake db:setup      
    - name: run Cucumber tests and capture coverage
      run: |
        bundle exec cucumber
        ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
    - name: run RSpec tests
      run: |
        bundle exec rspec
        ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
    - name: Publish code coverage
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
        ./cc-test-reporter upload-coverage --id "b27ddaa3e2284dc734d6b075bbf977e87c08861108dc5434a64c992c514bd43b"
        ./cc-test-reporter after-build --id "b27ddaa3e2284dc734d6b075bbf977e87c08861108dc5434a64c992c514bd43b"